# Generated by Django 5.2 on 2025-06-05 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingestion',
            fields=[
                ('ingestion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ids', models.JSONField()),
                ('status', models.CharField(choices=[('yet_to_start', 'yet_to_start'), ('triggered', 'triggered'), ('completed', 'completed')], default='yet_to_start', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='home.ingestion')),
            ],
        ),
    ]
